"""add ai_audit_logs/inference table

Revision ID: 05d7f800809e
Revises: 3a3d6cb391ad
Create Date: 2025-09-24 14:18:48.829354

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05d7f800809e'
down_revision: Union[str, Sequence[str], None] = '3a3d6cb391ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('requester_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requester_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sa.TEXT(), nullable=True),
    sa.Column('response_text', sa.TEXT(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_input_tokens'), 'ai_audit_logs', ['input_tokens'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_organization_id'), 'ai_audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_total_tokens'), 'ai_audit_logs', ['total_tokens'], unique=False)
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_audit_logs_total_tokens'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_organization_id'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_input_tokens'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###
