"""renamed to url_path to storage_key(afte understand that not has to do with url but with obj_key to download the file from s3)

Revision ID: 499b14665072
Revises: 1f85d408d127
Create Date: 2025-07-21 12:04:21.308957

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499b14665072'
down_revision: Union[str, Sequence[str], None] = '1f85d408d127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('documents', 'url_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('url_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
