"""add organization_id column to document_chunks (with FK and index)

Revision ID: 828f3e60efc5
Revises: db6675e51f36
Create Date: 2025-09-10 13:19:10.726649

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828f3e60efc5'
down_revision: Union[str, Sequence[str], None] = 'db6675e51f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'organization_id')
    # ### end Alembic commands ###
