"""some column renames on organizations

Revision ID: e5cab013b83c
Revises: 
Create Date: 2025-07-17 11:04:55.965072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5cab013b83c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_organizations_name_organization'), table_name='organizations')
    op.create_index(op.f('ix_organizations_organization_name'), 'organizations', ['organization_name'], unique=True)
    op.drop_column('organizations', 'name_organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('name_organization', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_organization_name'), table_name='organizations')
    op.create_index(op.f('ix_organizations_name_organization'), 'organizations', ['name_organization'], unique=True)
    op.drop_column('organizations', 'organization_name')
    # ### end Alembic commands ###
